name: pgplayer_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  file_picker: ^6.1.1
  http: ^1.1.0
  path_provider: ^2.1.1
  ffmpeg_kit_flutter: ^6.0.3
  url_launcher: ^6.2.2
  navigator: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.12

flutter:
  uses-material-design: true
  assets:
    # - assets/detector.exe
    # - assets/icon.png
    # - assets/ffmpeg/
    # - assets/ffmpeg/bin/
    # - assets/ffmpeg/bin/ffmpeg.exe
    # - assets/ffmpeg/bin/ffplay.exe
    # - assets/ffmpeg/bin/ffprobe.exe
    # - assets/ffmpeg/presets/libvpx-360p.ffpreset
    # - assets/ffmpeg/presets/libvpx-720p.ffpreset
    # - assets/ffmpeg/presets/libvpx-720p50_60.ffpreset
    # - assets/ffmpeg/presets/libvpx-1080p.ffpreset
    # - assets/ffmpeg/presets/libvpx-1080p50_60.ffpreset

msix_config:
  display_name: PGPlayer
  publisher_display_name: Eclectisoft

  identity_name: Eclectisoft.PGPlayer
  publisher: CN=0D201C07-2EE2-4B88-BEE4-41AEC65BE3EC

  msix_version: 1.1.0.0
  store: true

  capabilities: internetClient
  logo_path: assets/icon.png

